[package]
name = "diagram_base"
version = "0.1.0"
authors = ["Krzysztof Jagiello <me@kjagiello.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
